version: "3"
services:
  db:
    image: mysql:8.0
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "3306:3306"
    command:
      [
        '--character-set-server=utf8mb4',
        '--skip-character-set-client-handshake',
        '--collation-server=utf8mb4_unicode_ci'
      ]
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server-app
    ports:
      - "5000:5000"
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client-app
    ports:
      - "80:80"
