version: "3"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server-app
    depends_on:
      - db

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client-app
    ports:
      - "3000:80"
    depends_on:
      - server
